Apply temp. patch to Triton code to resolve conflicting cache dirs in TP case (#34)
We are seeing Mixtral pods with TP>1 failing with errors like:
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/vllm/.triton/cache/c926ad2ef143810ed738a313c473c7b2/fused_moe_kernel.cubin.tmp.pid_72_945989'
```
It seems like there is some conflict in the Triton cache directories
when using multi-processing. This has actually been
[fixed](https://github.com/triton-lang/triton/pull/3544) upstream in
Triton, but the fix hasn't made it into Triton v2.3.0 which is what vLLM
is currently using.

This change essentially applies same fix that has made it into Triton
main branch inside our container.

---------

Signed-off-by: Thomas Parnell <tpa@zurich.ibm.com>