Revert previous attempt at Triton patch; use CustomCacheManger approach instead. (#35)
I tested the previous fix for the Triton cache collision issue (see:
#34) and it didn't work.

I now see errors like:
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/vllm/.triton/cache/1feb415f3280ca46eea8c4407a58c23e/fused_moe_kernel.json.tmp.pid_72_c0a0033e-6147-4520-ae3a-3847d02598f8'
```
which now shows the `uuid` instead of a random integer, but problem
remains.

This PR implements a different workaround, proposed by @cyang49, that
tells Triton to use a custom cache manager which assigns a different
directory based on the process id.

This time I have tested it and it seems to work.

---------

Signed-off-by: Thomas Parnell <tpa@zurich.ibm.com>
Signed-off-by: Nick Hill <nickhill@us.ibm.com>
Signed-off-by: Joe Runde <joe@joerun.de>
Co-authored-by: Chih-Chieh-Yang <chih.chieh.yang@ibm.com>
Co-authored-by: Joe Runde <joseph.runde@ibm.com>
Co-authored-by: Nick Hill <nickhill@us.ibm.com>